name: test_cookieproj_astropy

channels:
    - defaults
    - conda-forge
    - astropy

dependencies:
    - python>=3.6
    - anaconda
    - sphinx >= 1.6
    - pip
    - pip:
        - GitPython
        - configparser
        - sphinx-astropy
